import { getVw } from "../../utils";

export const charTable = {
  "ani": {
    attackSrc: './ani-attack-1.png',
    attack2Src: './ani-attack-2.png',
    moveSrc: './ani-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "archer": {
    attackSrc: './archer-attack-1.png',
    attack2Src: './archer-attack-2.png',
    moveSrc: './archer-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "assa": {
    attackSrc: './assa-attack-1.png',
    attack2Src: './assa-attack-2.png',
    moveSrc: './assa-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "cleric": {
    attackSrc: './cleric-attack-1.png',
    attack2Src: './cleric-attack-2.png',
    moveSrc: './cleric-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "fighter": {
    attackSrc: './fighter-attack-1.png',
    attack2Src: './fighter-attack-2.png',
    moveSrc: './fighter-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "golem": {
    attackSrc: './golem-attack-1.png',
    attack2Src: './golem-attack-2.png',
    moveSrc: './golem-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "mega": {
    attackSrc: './mega-attack-1.png',
    attack2Src: './mega-attack-2.png',
    moveSrc: './mega-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "priest": {
    attackSrc: './priest-attack-1.png',
    attack2Src: './priest-attack-2.png',
    moveSrc: './priest-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "kunoichi": {
    attackSrc: './kunoichi-attack-1.png',
    attack2Src: './kunoichi-attack-2.png',
    moveSrc: './kunoichi-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "shaman": {
    attackSrc: './shaman-attack-1.png',
    attack2Src: './shaman-attack-2.png',
    moveSrc: './shaman-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "shinobi": {
    attackSrc: './shinobi-attack-1.png',
    attack2Src: './shinobi-attack-2.png',
    moveSrc: './shinobi-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "firemega": {
    attackSrc: './firemega-attack-1.png',
    attack2Src: './firemega-attack-2.png',
    moveSrc: './firemega-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "slime": {
    attackSrc: './slime-attack-1.png',
    attack2Src: './slime-attack-2.png',
    moveSrc: './slime-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "tank": {
    attackSrc: './tank-attack-1.png',
    attack2Src: './tank-attack-2.png',
    moveSrc: './tank-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "tree": {
    attackSrc: './tree-attack-1.png',
    attack2Src: './tree-attack-2.png',
    moveSrc: './tree-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  },
  "wizard": {
    attackSrc: './wizard-attack-1.png',
    attack2Src: './wizard-attack-2.png',
    moveSrc: './wizard-idle.png',
    moveWidth: getVw(300),
    moveHeight: getVw(150),
    attackWidth: getVw(300),
    attackHeight: getVw(150),
  }
} as const;
