
export const charTable = {
    "ani": {
        attackSrc: `./ani-attack-1.png`,
        moveSrc: `./ani-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "archer": {
        attackSrc: `./archer-attack-1.png`,
        moveSrc: `./archer-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "assa": {
        attackSrc: `./assa-attack-1.png`,
        moveSrc: `./assa-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "cleric": {
        attackSrc: `./cleric-attack-1.png`,
        moveSrc: `./cleric-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "fighter": {
        attackSrc: `./fighter-attack-1.png`,
        moveSrc: `./fighter-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "golem": {
        attackSrc: `./golem-attack-1.png`,
        moveSrc: `./golem-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "mega": {
        attackSrc: `./mega-attack-1.png`,
        moveSrc: `./mega-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",  
    },
    "priest": {
        attackSrc: `./priest-attack-1.png`,
        moveSrc: `./priest-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",  
    },
    "kunoichi": {
        attackSrc: `./kunoichi-attack-1.png`,
        moveSrc: `./kunoichi-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "shaman": {
        attackSrc: `./shaman-attack-1.png`,
        moveSrc: `./shaman-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "shinobi": {
        attackSrc: `./shinobi-attack-1.png`,
        moveSrc: `./shinobi-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "shman": {
        attackSrc: `./shman-attack-1.png`,
        moveSrc: `./shman-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "slime": {
        attackSrc: `./slime-attack-1.png`,
        moveSrc: `./slime-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "tank": {
        attackSrc: `./tank-attack-1.png`,
        moveSrc: `./tank-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "tree": {
        attackSrc: `./tree-attack-1.png`,
        moveSrc: `./tree-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "wizard": {
        attackSrc: `./wizard-attack-1.png`,
        moveSrc: `./wizard-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    }
} as const;
