
export const charTable = {
    "ani": {
        attackSrc: `./ani-attack-1.png`,
        attack2Src: './ani-attack-2.png',
        moveSrc: `./ani-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "archer": {
        attackSrc: `./archer-attack-1.png`,
        attack2Src: './archer-attack-2.png',
        moveSrc: `./archer-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "assa": {
        attackSrc: `./assa-attack-1.png`,
        attack2Src: './assa-attack-2.png',
        moveSrc: `./assa-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "cleric": {
        attackSrc: `./cleric-attack-1.png`,
        attack2Src: './cleric-attack-2.png',
        moveSrc: `./cleric-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "fighter": {
        attackSrc: `./fighter-attack-1.png`,
        attack2Src: './fighter-attack-2.png',
        moveSrc: `./fighter-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "golem": {
        attackSrc: `./golem-attack-1.png`,
        attack2Src: './golem-attack-2.png',
        moveSrc: `./golem-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "mega": {
        attackSrc: `./mega-attack-1.png`,
        attack2Src: './mega-attack-2.png',
        moveSrc: `./mega-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",  
    },
    "priest": {
        attackSrc: `./priest-attack-1.png`,
        attack2Src: './priest-attack-2.png',
        moveSrc: `./priest-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",  
    },
    "kunoichi": {
        attackSrc: `./kunoichi-attack-1.png`,
        attack2Src: './kunoichi-attack-2.png',
        moveSrc: `./kunoichi-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "shaman": {
        attackSrc: `./shaman-attack-1.png`,
        attack2Src: './shaman-attack-2.png',
        moveSrc: `./shaman-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "shinobi": {
        attackSrc: `./shinobi-attack-1.png`,
        attack2Src: './shinobi-attack-2.png',
        moveSrc: `./shinobi-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "firemega": {
        attackSrc: `./firemega-attack-1.png`,
        attack2Src: './firemega-attack-2.png',
        moveSrc: `./firemega-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "slime": {
        attackSrc: `./slime-attack-1.png`,
        attack2Src: './slime-attack-2.png',
        moveSrc: `./slime-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "tank": {
        attackSrc: `./tank-attack-1.png`,
        attack2Src: './tank-attack-2.png',
        moveSrc: `./tank-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "tree": {
        attackSrc: `./tree-attack-1.png`,
        attack2Src: './tree-attack-2.png',
        moveSrc: `./tree-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    },
    "wizard": {
        attackSrc: `./wizard-attack-1.png`,
        attack2Src: './wizard-attack-2.png',
        moveSrc: `./wizard-idle.png`,
        moveWidth: "300px",
        moveHeight: "150px",
        attackWidth: "300px",
        attackHeight: "150px",
    }
} as const;
