export const SKILL_DESCRIPTION: Record<string, string> = {
    "attack_lowest_hp": "Attack the enemy with the lowest HP, inflict $value points of HP damage.",
    "add_all_tmp_attack": "Add $value points of attack to all friendly units.",
    "reduce_all_tmp_attack": "Reduce $value points of attack from all enemy units.",
    "add_all_tmp_magic": "Add $value points of magic to all friendly units.",
    "add_all_tmp_hp": "Add $value points of HP to all friendly units.",
    "aoe": "Attack all enemy units, inflict $value points of HP damage.",
    "forbid_debuff": "Forbid all of the debuff from enemy",
    "forbid_buff": "Forbid all of the buff on enemy",
    "reduce_tmp_attack": "Reduce $value points of attack from enemy.",
    "add_all_tmp_max_magic": "Add $value points of max magic to all enemies.",
    "all_max_hp_to_back1": "Permanently add $value of max HP to the next friendly unit.",
    "attack_by_life_percent": "Inflict $value% of HP damage to enemy.",
    "attack_sputter_to_second_by_percent": "Attack the enemy and sputter the next enemy, inflict $value% attack point HP damage to the next enemy.",
    "attack_last_char": "Attack the last enemy.",
}