[package]
name = "chess_package"
version = "0.0.1"
published-at = "0x830c485a5963411f50ba3cb250556d4ef10dab5b09933a85bc5be31a429edae3"

[dependencies]
MoveStdlib = { local ="G:/autoChess/move_split/move-stdlib" }
Sui = { local = "G:/autoChess/move_split/sui-framework" }
util_package = { local = "G:/autoChess/myMoveVersion/myMoveVersion/util_package"}
role_package = { local = "G:/autoChess/myMoveVersion/myMoveVersion/role_package"}
lineup_package = { local = "G:/autoChess/myMoveVersion/myMoveVersion/lineup_package" }
challenge_package = { local = "G:/autoChess/myMoveVersion/myMoveVersion/challenge_package" }
fight_package = { local = "G:/autoChess/myMoveVersion/myMoveVersion/fight_package" }

[addresses]
chess_package = "0x830c485a5963411f50ba3cb250556d4ef10dab5b09933a85bc5be31a429edae3"
fight_package = "0xf1156dd5f688dc27d521af57aaa940a33b9766d14da3a83cdccb281af6f060b2"
util_package = "0x4dfe2c82a07832df3a6b15601dda007b2c4511d733bcb9a75eb3fa4419de61ce"
role_package = "0xa426d13e718c4a3e5a40e0eef246d52f1f9dbc773bc352e13fbba68d901606f9"
lineup_package = "0x1a90b2b03d2fcc761854081cbb308793e5590f8847a720f1efd5c570521f928b"
challenge_package = "0x2a94fe9ca377136a9a82407749aa5cb43cd0611319688a9d4ff6fa5cf1f953d1"
account = "0xbe379359ac6e9d0fc0b867f147f248f1c2d9fc019a9a708adfcbe15fc3130c18"