[package]
name = "chess_package"
version = "0.0.1"
published-at = "0x414579c433a436024e10785daf8ed58b2a3469de39d36a635912a1c9579f8ea3"

[dependencies]
Sui = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/sui-framework" }
MoveStdlib = { local ="/Users/siminxie/sui_dev/autoChess/myMoveVersion/move-stdlib" }
util_package = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/util_package" }
role_package = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/role_package" }
lineup_package = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/lineup_package" }
challenge_package = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/challenge_package" }
fight_package = { local = "/Users/siminxie/sui_dev/autoChess/myMoveVersion/fight_package" }

[addresses]
chess_package = "0x414579c433a436024e10785daf8ed58b2a3469de39d36a635912a1c9579f8ea3"
util_package = "0x25dbf0c35551d7a97d47a0d2cb493b728a7f8d46844b2c55dab0355b7c53778f"
role_package = "0x1c69f07380653053fcc86e2677b74845fa37478fe6a80b56a80dc19f38c13af2"
lineup_package = "0x0a17a2364118a774e140b522f6c9c6bbceb90daadced455a5111b77046ac4688"
challenge_package = "0x8c6a7073a82504ee4e011a0c1f35ba50417ea1a596bac140652a5f023632a33e"
fight_package = "0xbbed3ca8320e98b17cf87699da8bac754f146950aaaaad5ac32fd439f25bb009"
account = "0xbe379359ac6e9d0fc0b867f147f248f1c2d9fc019a9a708adfcbe15fc3130c18"