[package]
name = "chess_packagev2"
version = "0.0.1"
published-at = "0x830c485a5963411f50ba3cb250556d4ef10dab5b09933a85bc5be31a429edae3"

[dependencies]
MoveStdlib = { local ="G:/autoChess/move_split/move-stdlib" }
Sui = { local = "G:/autoChess/move_split/sui-framework" }
util_packagev2 = { local = "G:/autoChess/myMoveVersion/myMoveVersion/util_package"}
role_packagev2 = { local = "G:/autoChess/myMoveVersion/myMoveVersion/role_package"}
lineup_packagev2 = { local = "G:/autoChess/myMoveVersion/myMoveVersion/lineup_package" }
challenge_packagev2 = { local = "G:/autoChess/myMoveVersion/myMoveVersion/challenge_package" }
fight_packagev2 = { local = "G:/autoChess/myMoveVersion/myMoveVersion/fight_package" }
chess_package_main = { local = "G:/autoChess/move_split/chess_package_main" }

[addresses]
chess_packagev2 = "0x830c485a5963411f50ba3cb250556d4ef10dab5b09933a85bc5be31a429edae3"
fight_packagev2 = "0xf1156dd5f688dc27d521af57aaa940a33b9766d14da3a83cdccb281af6f060b2"
util_packagev2 = "0x4dfe2c82a07832df3a6b15601dda007b2c4511d733bcb9a75eb3fa4419de61ce"
role_packagev2 = "0xa426d13e718c4a3e5a40e0eef246d52f1f9dbc773bc352e13fbba68d901606f9"
lineup_packagev2 = "0x1a90b2b03d2fcc761854081cbb308793e5590f8847a720f1efd5c570521f928b"
challenge_packagev2 = "0x2a94fe9ca377136a9a82407749aa5cb43cd0611319688a9d4ff6fa5cf1f953d1"
manager = "0xbe379359ac6e9d0fc0b867f147f248f1c2d9fc019a9a708adfcbe15fc3130c18"
chess_package_main = "0xc6771aebae85d27ea3176be5a31c0b15927e4c5efa0add413b6cbbe0730fbdeb"